name: close_the_ramp_protocol
description: Offline-first Flutter app for Close the Ramp â€” Protocol.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.68.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  share_plus: ^10.0.2
  path_provider: ^2.1.3
  file_picker: ^8.0.2
  audioplayers: ^6.0.0
  flutter_local_notifications: ^17.1.2
  collection: ^1.18.0
  uuid: ^4.4.0
  timezone: ^0.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/sounds/alarm_soft.mp3
    - assets/sounds/alarm_strong.mp3
    - assets/sounds/alarm_extreme.mp3
